name: JNI Bind Build/Test Status

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ubuntu_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: bazel test --cxxopt='-std=c++17' --repo_env=CC=clang ...

  macos_test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: bazel test --cxxopt='-std=c++17' --repo_env=CC=clang ...
